name: kariyer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  flutter_svg: any # Eklendi

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: # Eklendi
    - assets/ # assets klasörünüzdeki tüm dosyaları içerir
