name: kariyer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.9.0
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  flutter_svg: any
  flutter_phone_direct_caller: ^2.0.1
  mask_text_input_formatter: ^2.4.0
  url_launcher: ^6.2.5
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.0
  location: ^5.0.3
  geocoding: ^2.1.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: # Eklendi
    - assets/ # assets klasörünüzdeki tüm dosyaları içerir
